lezioni/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),


    path('corsi/', views.corsi, name='corsi'),
    path('corsi/<int:id>/lezioni/', views.lezioni, name='lezioni'),
    path('corsi/lezioni/<int:id>/', views.dettaglio_lezione, name='dettaglio_lezione'),


    path('mostra/targhetta/<targa>/', views.mostra_targa, name='mostra_targa'),
]

registro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('lezioni.urls')),
    path('admin/', admin.site.urls),
]

lezioni/models.py
from django.db import models


class Corso(models.Model):
    titolo = models.CharField(max_length=400)
    codice = models.CharField(max_length=20)
    data_inizio = models.DateField()
    data_fine = models.DateField()


    def numero_iscritti(self):
        return 'Nessuno'

    def __str__(self):
        return self.titolo
    
    class Meta:
        verbose_name_plural = 'Corsi'
        ordering = ['-data_inizio']



class Persona(models.Model):
    nome = models.CharField(max_length=200)
    cognome = models.CharField(max_length=200)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.nome + ' ' + self.cognome
    
    class Meta:
        verbose_name_plural = 'Persone'
        ordering = ['cognome', 'nome']


class Modulo(models.Model):
    nome = models.CharField(max_length=100)
    corso = models.ForeignKey(Corso, on_delete=models.PROTECT, related_name="moduli")

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = 'Moduli'



class Materia(models.Model):
    nome = models.CharField(max_length=100)
    modulo = models.ForeignKey(Modulo, on_delete=models.PROTECT, related_name="materie")
    docente = models.ForeignKey(Persona, on_delete=models.PROTECT, null=True, blank=True, related_name='materie')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name_plural = 'Materie'


class Lezione(models.Model):

    TIPI_LEZIONE = (
        (None, 'Seleziona...'),
        ('T', 'Teoria'),
        ('P', 'Pratica'),
    )

    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, related_name="lezioni")
    argomento = models.TextField(verbose_name="Di cosa avete parlato?", null=True, blank=True, help_text="Scrivi almeno 3 parole")
    data = models.DateField()
    online = models.BooleanField(default=False)
    tipologia = models.CharField(max_length=1, choices=TIPI_LEZIONE, null=True)
    ora_inizio = models.TimeField(null=True, blank=True)
    ora_fine = models.TimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.materia} del {self.data}'
    

    def durata(self):
        from datetime import datetime, date
        if self.ora_inizio and self.ora_fine:
            return datetime.combine(date.today(), self.ora_fine) - datetime.combine(date.today(), self.ora_inizio)


    def prossima(self):
        corso = self.materia.modulo.corso
        return Lezione.objects.filter(materia__modulo__corso=corso, data__gt=self.data).order_by('data').first()

    def precedente(self):
        corso = self.materia.modulo.corso
        return Lezione.objects.filter(materia__modulo__corso=corso, data__lt=self.data).order_by('data').last()
    
    class Meta:
        verbose_name_plural = 'Lezioni'
        ordering = ['-data']


class Presenza(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT, related_name="presenze")
    lezione = models.ForeignKey(Lezione, on_delete=models.PROTECT, related_name="presenze")

    def __str__(self):
        return f'{self.persona} - {self.lezione}'
    
    class Meta:
        verbose_name_plural = 'Presenze'
        ordering = ['persona', 'lezione']
        unique_together = ['persona', 'lezione']


class Iscrizione(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT)
    corso = models.ForeignKey(Corso, on_delete=models.PROTECT, related_name="iscrizioni")
    data_iscrizione = models.DateField()
    data_ritiro = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'{self.persona} - {self.corso}'
    
    class Meta:
        verbose_name_plural = 'Iscrizioni'
        ordering = ['persona', 'corso']

lezioni/forms.py
from django import forms
from .models import Lezione

class LezioneForm(forms.ModelForm):

    class Meta:
        model = Lezione
        fields = '__all__'
        widgets = {
            'data': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'class': 'form-control', 
                    'type': 'date'
                    }),
            'ora_inizio': forms.TimeInput(
                attrs={'class': 'form-control', 
                    'type': 'time'
                    }),
            'tipologia': forms.RadioSelect
        }

lezioni/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import *


def index(request):
    from random import randint
    totale_gatti = randint(0, 44)
    lista_gatti = range(totale_gatti)
    persone = Persona.objects.all()

    context = {
        'nome': 'Nello',
        'cognome': 'Polesello',
        'totale_gatti': totale_gatti,
        'lista_gatti': lista_gatti,
        'presenti': 6,
        'persone': persone,
    }

    print(context)
    return render(request, 'homepage.html', context)


def index_old(request):
    if 'one' in request.path:
        return HttpResponse("<h1 style='color:red'>Ciaone</h1>")
    else:
        return HttpResponse("<h4>Ciao</h4>")
    


def mostra_targa(request, targa):

    prossima = 'cc123aa'
    valid = targa[:2].isalpha() and targa[2:5].isdigit() and targa[5:].isalpha()
    square = False
    if len(targa) == 7 and valid:
        targa = targa.upper()

        prossima = targa[:2] + str(int(targa[2:5]) + 1).zfill(3) + targa[5:]

        targa = targa[:2] + ' &nbsp; ' + targa[2:]
        square = targa.startswith('Z')

    context = {
        'targa': targa,
        'valid': valid,
        'square': square,
        'prossima': prossima,
    }
    return render(request, 'targa.html', context)


def corsi(request):
    context = {
        'corsi': Corso.objects.all(),
    }
    return render(request, 'corsi.html', context)


def lezioni(request, id):
    import openpyxl

    corso = Corso.objects.get(id=id)
    lezioni = Lezione.objects.filter(materia__modulo__corso=corso).order_by('data')

    if 'excel' in request.GET:

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = corso.titolo

        c = ws.cell(row=2, column=3)
        c.value = 'CIAO'

        for i, lezione in enumerate(lezioni):
            c = ws.cell(row=i+1, column=1) 
            c.value = lezione.argomento

            c = ws.cell(row=i+1, column=2) 
            c.value = lezione.materia.nome

        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'inline; filename=calendario.xlsx'
        
        wb.save(response)

        return response
    
    context = {
        'corso': corso,
        'lezioni': lezioni
    }
    return render(request, 'lezioni.html', context)


def dettaglio_lezione(request, id):
    from .forms import LezioneForm

    lezione = Lezione.objects.get(id=id)

    form = LezioneForm(request.POST or None, instance=lezione)

    presenti = request.POST.getlist('presente')
    print('presenti ' , presenti )

    if request.method == 'POST':

        # Salva i dati della lezione
        if 'salva-dettagli' in request.POST:
            if form.is_valid():
                form.save()
            





        # Salva i presenti alla lezione
        if 'salva-presenze' in request.POST:
            Presenza.objects.filter(lezione=lezione).delete()

            for id_persona in presenti:
                presenza = Presenza(lezione=lezione, persona_id=id_persona)
                presenza.save()

            return redirect(request.path)
        



    persone_presenti = Persona.objects.filter(presenze__lezione = lezione)
    context = {'lezione': lezione, 'persone_presenti':persone_presenti, 'form':form}
    return render(request, 'dettaglio_lezione.html', context)

lezioni/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}Evviva Django{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css" integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link rel="stylesheet" href="{% static 'lezioni/css/style.css' %}">
</head>
<body>
    {% include 'header.html' %}

    {% block breadcrumbs %}
    <div id="breadcrumbs">
        <div class="container">
            <a href="{% url 'corsi' %}">Corsi</a>
        </div>
    </div>
    {% endblock %}
    <div class="container">
       
        {% block content %}
            <h1>Qua ci va tanta bella roba</h1>
        {% endblock %}
    </div>
</body>
</html>

lezioni/templates/corsi.html
{% extends 'base.html' %}

{% block page_title %}Lista corsi{% endblock %}


{% block content %}
<h1>Ma che bel sito!</h1>

    <div class="row">
        <h1>Lista corsi belli</h1>

        {% for corso in corsi %}
            <div class="col-lg-4">
                <a href="{% url 'lezioni' corso.pk %}">
                    <div class="corso">
                        <h2>{{corso.titolo}}</h2>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

lezioni/templates/dettaglio_lezione.html
{% extends 'base.html' %}

{% block page_title %}{{lezione}}{% endblock %}


{% block breadcrumbs %}

{% with corso=lezione.materia.modulo.corso %}
<div id="breadcrumbs">
    <div class="container">
        <a href="{% url 'corsi' %}">Corsi</a> ›
        <a href="{% url 'lezioni' corso.pk %}">{{corso}}</a> ›
        <strong>{{lezione}}</strong>
    </div>
</div>
{% endwith %}

{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <h2>Presenze</h2>

<form method="PoSt">

    {% csrf_token %}
    <ul id="presenze">
        {% for iscrizione in lezione.materia.modulo.corso.iscrizioni.all %}
        <li>
            <input type="checkbox" name="presente" value="{{iscrizione.persona.pk}}" id="ciccio-{{forloop.counter}}" {% if iscrizione.persona in persone_presenti %} checked{% endif %}>
            <label for="ciccio-{{forloop.counter}}">{{iscrizione.persona}}</label>
        </li>
        {% endfor %}
    </ul>
    <input class="btn btn-success" type="submit" name="salva-presenze" value="Invia">

</form>


<nav class="mt-4 text-center">
    <a {% if lezione.precedente %} href="{% url 'dettaglio_lezione' lezione.precedente.pk %}"{% endif %} class="btn {% if lezione.precedente %}btn-dark{% else %}invisible{% endif %}" title="{{lezione.precedente}}">&larr;</a>
    <a {% if lezione.prossima %} href="{% url 'dettaglio_lezione' lezione.prossima.pk %}"{% endif %} class="btn {% if lezione.prossima %}btn-dark{% else %}invisible{% endif %}" title="{{lezione.prossima}}">&rarr;</a>
</nav>

        </div>
        <div class="col-lg-6">

            <hr>

{% if request.user.is_authenticated %}
<form method="post" novalidate>
    {% csrf_token %}
    <table class="table">
        {{form.as_table}}
    </table>
    <input type="submit" name="salva-dettagli" value="Salva" class="btn btn-success">
</form>
{% endif %}

            <h1>Data: {{lezione.data|date:'j/n/Y'}}</h1>

            <p>Tipo lezione: <strong>{{lezione.get_tipologia_display}}</strong></p>
            <p>Materia: <strong>{{lezione.materia}}</strong></p>
            <p>Argomento: <strong>{{lezione.argomento}}</strong></p>
            <p>Dalle <strong>{{lezione.ora_inizio|default:'--:--'}}</strong> alle <strong>{{lezione.ora_fine|default:'--:--'}}</strong></p>
            <p>Durata: {{lezione.durata}}</p>

            <p>Firma del docente ({{ lezione.materia.docente }})  __________________</p>
        </div>
    </div>
{% endblock %}

lezioni/templates/header.html
{% load static %}
<header>
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <img src="{% static 'lezioni/images/cff.png' %}" alt="Friuli Formazione">

                <a href="{% url 'corsi' %}">Home page</a>

                {{request.user.is_authenticated}}
            </div>
        </div>
    </div>
</header>

lezioni/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evviva Django</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css" integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="container">
        <h1>Che bellezza!</h1>

        <h2>Ciao, {{user}}</h2>
        <p>Il mio primo template</p>

        Ci sono <strong><big>{{    totale_gatti  }}</big></strong> gatti in questo sito
        <p>
            {% if totale_gatti < 22 %}
                Sono pochi
                            {% else %}
                Sono tanti
    {% endif %}
        </p>    

        {% if totale_gatti < presenti %}
            <div class="alert alert-danger">Non ci sono abbastanza gatti</div>
        {% else %}
            <div class="alert alert-success">Abbiamo abbastanza gatti</div>
        {% endif %}

        <progress style="width: 100%;" value="{{totale_gatti}}" max="44"> 32% </progress>

<div class="row">
{% for persona in persone %}
<div class="col-lg-4 mb-4">
    <div class="card card-body bg-light h-100">
        <img src="https://wips.plug.it/cips/supereva/cms/2016/06/gatto-1.jpg" alt="" style="height: 150px; width: 100%; object-fit: cover;">
        <h3>{{forloop.counter}}.  {{persona.nome}} {{persona.cognome}}</h3>
    </div>
</div>
{% endfor %}
</div>

        {% comment %}
        {% for gatto in lista_gatti %}

<img src="https://wips.plug.it/cips/supereva/cms/2016/06/gatto-1.jpg" alt="" height="60">
        {% endfor %}
        {% endcomment %}

    </div>

</body>
</html>

lezioni/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evviva Django</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css" integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="container">
        <h1>Che bellezza!</h1>

        <h2>Ciao, {{nome.upper }} {{cognome}}</h2>
        <p>Il mio primo template</p>

        Ci sono <strong><big>{{totale_gatti}}</big></strong> gatti in questo sito
        <p>
            {% if totale_gatti < 22 %}
                Sono pochi
            {% else %}
                Sono tanti
            {% endif %}
        </p>    

        {% if totale_gatti < presenti %}
            <div class="alert alert-danger">Non ci sono abbastanza gatti</div>
        {% else %}
            <div class="alert alert-success">Abbiamo abbastanza gatti</div>
        {% endif %}

        <progress style="width: 100%;" value="{{totale_gatti}}" max="44"> 32% </progress>

<div class="row">
{% for persona in persone %}
<div class="col-lg-4 mb-4">
    <div class="card card-body bg-light h-100">
        <img src="https://wips.plug.it/cips/supereva/cms/2016/06/gatto-1.jpg" alt="" style="height: 150px; width: 100%; object-fit: cover;">
        <h3>{{persona.nome}} {{persona.cognome}}</h3>
    </div>
</div>
{% endfor %}
</div>

        {% comment %}
        {% for gatto in lista_gatti %}

<img src="https://wips.plug.it/cips/supereva/cms/2016/06/gatto-1.jpg" alt="" height="60">
        {% endfor %}
        {% endcomment %}

    </div>

</body>
</html>

lezioni/templates/lezioni.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<div id="breadcrumbs">
    <div class="container">
        <a href="{% url 'corsi' %}">Corsi</a> › <strong>{{corso}}</strong>
    </div>
</div>
{% endblock %}



{% block content %}

<a href="?excel" class="btn btn-success">Esporta in Excel</a>

<div class="row">
    <h1>Lista lezioni</h1>
        <h2>{{corso}}</h2>
    <table class="table">
        <tr>
            <th>Data</th>
            <th>Materia</th>
            <th>Inizio, fine</th>
            <th>Durata</th>
            <th>Presenze</th>
        </tr>
    {% for lezione in lezioni %}
        <tr>
            <td><a href="{% url 'dettaglio_lezione' lezione.pk %}">{{lezione.data}}</a></td>
            <td>{{lezione.materia}}</td>
            <td>{{lezione.ora_inizio}} — {{lezione.ora_fine}}</td>
            <td>{{lezione.durata}}</td>
            <td>{{lezione.presenze.count}}</td>
        </tr>
    {% endfor %}
    </table>
</div>
{% endblock content %}

lezioni/templates/targa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evviva Django</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css" integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        #targa {
            font-size: 100px;
            font-weight: bold;
            padding: 10px;
            margin: 30px;
            text-align: center;
            border: 1px solid #333;
            border-radius: 10px;
            position: relative;
            width: 800px;
        }
        #targa::before {
            content: "";
            display: block;
            position: absolute;
            background-color: #224c9a;
            top: 0;
            height: 100%;
            width: 50px;
            left: 0;
            border-radius: 10px 0 0 10px;
        }

        #targa.square {
            width: 500px;
        }
    </style>
</head>
<body>
    <div class="container">
    
        {% if valid %}
        <div id="targa"{% if square %} class="square"{% endif %}>
            {{targa|safe}}
        </div>
        {% else %}
        <div class="alert alert-danger">
            Targa non valida
        </div>
        {% endif %}



    <a href="{% url 'mostra_targa' prossima %}" class="btn btn-success">Prossima</a>
</div>

    {% if square %}

<script>
    alert("La targa è quadrata, hai una Jeep?")
</script>

    {% endif %}

</body>
</html>